# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: database-tasks 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "database-tasks"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Sam Reh"]
  s.date = "2015-05-20"
  s.description = "Rake tasks for Sequel ORM including dropping, creating and migrating"
  s.email = "samuelreh@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/database-tasks.rb",
    "lib/tasks/db.rake"
  ]
  s.homepage = "http://github.com/samuelreh/database-tasks"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Rake tasks for Sequel ORM"

  s.add_dependency 'sequel', '~> 5'
end

